name: Build mufeng-front and deploy to aliyun
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - master
jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@master
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete' # easingthemes/ssh-deploy使用的参数
          SOURCE: dist # 这是要复制到阿里云静态服务器的文件夹名称，此例中指的是npm run build之后生成的dist目录
          REMOTE_HOST: '120.25.195.171' # 你的阿里云公网地址
          REMOTE_USER: root # 阿里云登录后默认为 root 用户
          TARGET: /home/Web # 打包后的 dist 文件夹将放在 /home/mufeng-front